server:
  port: ${port:8111}
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1

spring:
  application:
    name: auth-service # nacos时候配置的
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.10.9:8848


