server:
  port: 7001
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1

spring:
  profiles:
    active: dev
  banner:
    location: classpath:banner/banner.txt


# 配置日志级别
logging:
  level:
    root: info
